### ISSUE TITLE
502 Bad Gateway while using Azure MFA authentication

### ISSUE THREAD

**Issue by rogerioefonseca** [louketo/louketo-proxy#540]
Hello guys,
I'm working on a strange behavior while using Gatekeeper to authenticate on Azure A.D.
So, for some strange reason when MFA is enabled for a user, it does not work and gets redirected to a 502 bad gateway page.
I'll post the HEADER changes in a minute, but if someone knows something about that, please let me know.
I'm using  version 8.0.1

**Comment by rogerioefonseca** [comment]
As information,  I upgraded that to 9.0.3 version and still not working.
:(

**Comment by jangaraj** [comment]
You didn't provided any details about the used config, infrastructure setup and promised header changes.

No details, so blind guess: you are reaching some connection timeouts, for example your upstream app is huge, slow Java app, which needs 15+ seconds to process initial request and it if failing as well, because Gatekeeper forwards huge access token in the request header to that app.

**Comment by rogerioefonseca** [comment]
Hey, thanks, you are right, It was pretty difficult to analyze,
Fortunately, we were able to fix the issue, and actually it was related to the Nginx buffer while dealing with some huge headers:
In the end, we just needed to increase proxy_buffer_size to 8k in Nginx, since the default is 4 in our platform.

https://andrewlock.net/fixing-nginx-upstream-sent-too-big-header-error-when-running-an-ingress-controller-in-kubernetes/

I hope It can help someone else there.

**Comment by jangaraj** [comment]
Are you really sure that 8k is enough for all your users? I have had users/clients, where generated access token can have ~50k size. I would use the size of your longest group name x 200 (because Azure OIDC client can deliver max 200 groups) and you will get groups size which you can get in the worst case.

**Comment by rogerioefonseca** [comment]
Good point,
Actually, now we decided to not increase it too much to have an idea of how these tokens' sizes are being generated.
It is working so far, but we will keep an eye on that.
Thanks

**Comment by rogerioefonseca** [comment]
So, please, close this ticket

**Comment by abstractj** [comment]
Closing it, thanks @jangaraj helping on this.

**Comment by AMoghrabi** [comment]
@rogerioefonseca May I ask how you got it working with Azure AD?

My problem is that Azure expects the client ID to have `spn:` prepended to it. The proxy does not like that though:

```
JWT claims invalid: invalid claims, 'aud' claim and 'client_id' do not match, aud={client_id}, client_id=spn:{client_id}"}
```

Likewise, if I remove `spn` from the keycloak `client_id`, then keycloak works fine but the token generated will not work because the api-server expects the `spn:` portion.


Would appreciate your guidance.

**Comment by rogerioefonseca** [comment]
So, @AMoghrabi honestly I'm just using the **client_id** from the Azure apps code and passing this parameter as ENV variable, I did not had any blockers regarding to SPN.
To put us on the same page, I'm using this image: quay.io/keycloak/keycloak-gatekeeper:8.0.1 as a NodePort on k8s Cluster and passing the parameters as variables like for example:
   ```
      PROXY_LISTEN
      PROXY_DISCOVERY_URL
      PROXY_CLIENT_ID
      PROXY_CLIENT_SECRET
      PROXY_ENABLE_REFRESH_TOKEN  
```

**Comment by AMoghrabi** [comment]
Thanks @rogerioefonseca , appreciate it.

Seems like I'm using the same parameters except I'm passing them in as `args`, not environment variables. I'll try it your way regardless.

I tried targeting version 8.0.1, no luck. 

May I ask if you're in the cloud or on-prem? 

Thanks!

**Comment by rogerioefonseca** [comment]
I'm sorry about the delay in the reply, but we are using a cloud solution.
:)



Rogério Esteves Fonseca
teccross.com.br
+55 61 9828-4163
skypeId: rogerio_fonseca4


Am Di., 30. Juni 2020 um 17:25 Uhr schrieb Ali Moghrabi <
notifications@github.com>:
