### ISSUE TITLE
Migrate Gatekeeper Docker image to Louketo

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#609]
## Summary 

The Gatekeeper codebase was moved to Louketo organization, now we need to move also the Dockerfile from the [Keycloak repository](https://github.com/keycloak/keycloak-containers/tree/master/gatekeeper) to the main repository.

## Why?

People should be able to pull the Louketo image from quay.io

## How

1. Create a prerelease `1.0.0-alpha` of Louketo and publish the binaries
2. Move the Dockerfile to Louketo repository doing all the changes necessary to use the released binaries

* Another option:
  - Use the same approach from oauth2-proxy repository and build the project with the image. See: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/Dockerfile

## Acceptance criteria

* [ ] Container image available on `quay.io/louketo/louketo-proxy`
* [ ] Have all the docs updated

## Additional Information

* Affects: #606, #541 and #530
* Blocks: pull request #608

**Comment by abstractj** [comment]
@stianst @JoelSpeed at some point we need to move the Dockerfile from https://github.com/keycloak/keycloak-containers/blob/master/gatekeeper/Dockerfile to the main repository, what do you guys prefer:

1. Hold it until the first release of Louketo
2. Move it as is with the references to Gatekeeper

I'd go with 2, but I don't want to rush into things.

**Comment by JoelSpeed** [comment]
What is the benefit to keeping the references to Gatekeeper if we move it now?

**Comment by abstractj** [comment]
> What is the benefit to keeping the references to Gatekeeper if we move it now?

Test the build process on quay.io and provide a way for people to build their own Docker image. But after thinking for a bit, I believe the approach you guys used here is better https://github.com/oauth2-proxy/oauth2-proxy/blob/master/Dockerfile.

I will remove the assignee for now, so if you guys would like to contribute, please let me know.

**Comment by abstractj** [comment]
@ASzc the summary is just an overall idea, but whatever ideas you have in mind will be more than welcome. Please let me know if this is something you would like to work, and I can think about other tasks.

**Comment by ASzc** [comment]
Building inside the image build works for operators and other container-exclusive stuff. However, I don't really like it when the software is also available in a non-container format, since you could end up with different binaries for the same version of the software. I did some quick searches to see if golang offers deterministic compilation, and it seems like yes, but only with Go 1.13 or later, and the `-trimpath` flag. So, maybe building inside the image build would work.

It would make sense to integrate with #616. It would publish binaries here on GitHub. Maybe it could update a Dockerfile and release an image from that too. I will see.

**Comment by abstractj** [comment]
@ASzc +1 about building it inside the image. Regards #616, I believe we can do it in small chunks, first get it merged, later iterate over the changes and add the Docker parts. 
I'm not sure if this is something you would like to try, but worth to mention that GoReleaser provides some support to Docker https://goreleaser.com/customization/docker/#publishing-to-multiple-docker-registries

**Comment by stianst** [comment]
I would not build Louketo within the image, but rather used the pre-built binary. Further, I would go for the GitHub Actions release workflow to upload images to Quay, and not make Quay auto build. We should also upload images to Docker Hub, which means it is best if we build images in the GitHub Actions workflow than depend on Quay auto-builds.

**Comment by JoelSpeed** [comment]
> I would not build Louketo within the image, but rather used the pre-built binary.

@stianst Could you explain your motivation for this? What drawbacks does building within the image bring?

**Comment by stianst** [comment]
As part of a release you need to build the binary, then build the image. Building the binary twice means there can be differences in the distributions, but also means that you end up requiring to build the binaries twice when doing a release.

I'll twist this around and ask you what are the benefits of building the binaries within the container?

**Comment by JoelSpeed** [comment]
> As part of a release you need to build the binary, then build the image. Building the binary twice means there can be differences in the distributions, but also means that you end up requiring to build the binaries twice when doing a release.

That makes sense, though I would have thought that there shouldn't be differences between building the same binary twice? In OAuth2 Proxy for example, we call `make build` within the Dockerfile builder image (multi-stage) so the command creating the build should be the same inside and outside the container

> I'll twist this around and ask you what are the benefits of building the binaries within the container?

It can be less error prone in my experience, for example, what happens if a mac user is building the binary for their use when debugging on their machine, then they build the image, it will pull in that darwin binary and try to execute it under linux, which causes confusing errors. (This is more of a developer experience than release process though)

For me, I prefer building in the image as it is a more reproducible environment, I can run the same docker build on any machine and it doesn't matter what else I have on my system, I'll get a functional docker image at the end

I appreciate the double build argument, I had considered in the past about building in images, then extracting the binary from the images to create the release artifacts, a kind of happy middle ground

**Comment by jangaraj** [comment]
+1 about building it inside the image. I use the same. Builder image defines only major Golang version (e.g. `golang:1.14`) so weekly CI builds use the latest minor golang versions automatically. Some my users need standalone binary, so I just start container at the end of CI build and run `docker cp` to get binary from the image = standalone binary is the same as binary included in the Docker image.

**Comment by stianst** [comment]
Building within the image makes perfect sense for developers - what could make most sense is to by default build in the image with a multi-stage build (as to be multi-stage as you don't want Go, etc. installed in the final image), then for releases we can add a build-arg that allows overriding that behaviour and instead add the binary from the release build. Extracting the binary from the image is an interesting alternative as well.

**Comment by ASzc** [comment]
Building inside and extracting is acceptable for avoiding two builds. We'd have to see if Github Actions can support that to implement #616-like behaviour with that modification.

However, if louketo is productised in the future, it will have to be built in the traditional fashion: build binary, then build container. Build-in-image can't be locked down enough, or access the right alignment tools, to meet product requirements.

**Comment by stianst** [comment]
With that in mind I would suggest we go with some sort of build argument where you can either build within image for dev purpose, and at the same time build by supplying the binary for release/productization purposes.

**Comment by ASzc** [comment]
The description is somewhat ambiguous on this point: Are we looking for the Dockerfile and associated kube yamls to end up in the louketo-proxy repo, or in a separate repo under the louketo organization?

Thinking about it from a prod build perspective, it is convention that the two are separate, but I think it could be accommodated if they were in the same repo.

**Comment by abstractj** [comment]
@ASzc That was just an initial idea, but I trust on your judgment, feel free to change the description to what you think it's best.

**Comment by ASzc** [comment]
Filed a PR #638
