### ISSUE TITLE
Release notes for 1.0.0-alpha.1

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#639]
Tag version: 1.0.0-alpha.1
Release title: 1.0.0-alpha.1

Today, we are happy to announce the first release of Louketo. As planned [some time ago](https://groups.google.com/forum/#!msg/keycloak-dev/oDyw94BWxM0/zc0J9R10BwAJ) the Gatekeeper repository was renamed to Louketo Proxy and now has a new home. This will enable us to build together with the OSS community a neutral and fully standard-based proxy solution with application developers in mind.

## What's New in Version 1.0.0-alpha.1

* Refactor of the codebase
* Migration of all the documentation from the Keycloak to Louketo organization
* Upgrade of some deprecated dependencies
* A set of bug fixes and improvements
* We also spent some time automating most of the stuff to pave the way for future releases

## Changelog

* 3f64894 Make equality fuzzy in TestGetWithin (#631)
* 48c72c0 Update to user-guide.md (#632)
* 33c23da Use HTTP 303 for redirects, instead HTTP 307 (#627)
* 9fd264c Automate Louketo releases (#615)
* f623dee Pass URI path upstream verbatim (#528 #483)
* a0cad52 Migrate Gatekeeper documentation to Louketo repository (#610)
* 9079de6 GH templates for bug reports and feature requests are not working (#617)
* 3905412 Replace satori/go.uuid by gofrs/uuid (#611)
* 906a8fe Create a GitHub templates for pull-requests and new issues #522
* 8e8510a Run golangci-lint as part of pull request workflow #604
* c500821 Migrate the codebase from Gatekeeper repository #516

**Comment by abstractj** [comment]
@ASzc @stianst could you please review the release notes that will be published tomorrow? The changelog should be automated, but I found a bug that we need to fix in the next releases.

**Comment by ASzc** [comment]
Will the release automation accept a version with a qualifier? I know it didn't like a pure alphabetic tag when I tested it before.

Technically if we want "OSGI format" (if that even makes sense in the context of golang), then `1.0.0-alpha.1` would be better represented as `1.0.0.alpha-1`. That's from Java-land though, not sure if Go likes four-part versions.

I notice you're missing `a0cad52 Migrate Gatekeeper documentation to Louketo repository (#610)` from the list, but maybe that's intentional.

`3f64894 Make equality fuzzy in TestGetWithin (#631)` also is missing, and I see it was merged to master a few days ago.

**Comment by abstractj** [comment]
@ASzc thanks for reviewing it Alex. `1.0.0.alpha.1` complies with the semantic version specification. So we should be good to go.
See: https://semver.org/#spec-item-9 and https://semver.org/#spec-item-11

Regards `3f64894 Make equality fuzzy in TestGetWithin (#631)`, it's the first item in the changelog. But please let me know if any other thing should be updated.

About `a0cad52 Migrate Gatekeeper documentation to Louketo repository (#610)`, updated the document. Thanks for that.

**Comment by abstractj** [comment]
Resolved and released here https://github.com/louketo/louketo-proxy/releases/tag/1.0.0-alpha.1
